/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudentAssessmentsRouteImport } from './routes/student/assessments'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/student/assessments',
  path: '/student/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/student/assessments'
    | '/student/courses'
    | '/student/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/student/assessments'
    | '/student/courses'
    | '/student/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/student/assessments'
    | '/student/courses'
    | '/student/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/student/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
