/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminAcademicRouteImport } from './routes/admin/academic'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminStatisticsRouteImport } from './routes/admin/statistics'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as LecturerAssessmentsRouteImport } from './routes/lecturer/assessments'
import { Route as LecturerCoursesRouteImport } from './routes/lecturer/courses'
import { Route as LecturerDashboardRouteImport } from './routes/lecturer/dashboard'
import { Route as LecturerGradingRouteImport } from './routes/lecturer/grading'
import { Route as LecturerMaterialsRouteImport } from './routes/lecturer/materials'
import { Route as LecturerProfileRouteImport } from './routes/lecturer/profile'
import { Route as LecturerStatisticsRouteImport } from './routes/lecturer/statistics'
import { Route as LecturerSubmissionsRouteImport } from './routes/lecturer/submissions'
import { Route as StudentAssessmentsRouteImport } from './routes/student/assessments'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentGradesRouteImport } from './routes/student/grades'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentSubmissionsRouteImport } from './routes/student/submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicRoute = AdminAcademicRouteImport.update({
  id: '/admin/academic',
  path: '/admin/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerAssessmentsRoute = LecturerAssessmentsRouteImport.update({
  id: '/lecturer/assessments',
  path: '/lecturer/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerCoursesRoute = LecturerCoursesRouteImport.update({
  id: '/lecturer/courses',
  path: '/lecturer/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerDashboardRoute = LecturerDashboardRouteImport.update({
  id: '/lecturer/dashboard',
  path: '/lecturer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerGradingRoute = LecturerGradingRouteImport.update({
  id: '/lecturer/grading',
  path: '/lecturer/grading',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerMaterialsRoute = LecturerMaterialsRouteImport.update({
  id: '/lecturer/materials',
  path: '/lecturer/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerProfileRoute = LecturerProfileRouteImport.update({
  id: '/lecturer/profile',
  path: '/lecturer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerStatisticsRoute = LecturerStatisticsRouteImport.update({
  id: '/lecturer/statistics',
  path: '/lecturer/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerSubmissionsRoute = LecturerSubmissionsRouteImport.update({
  id: '/lecturer/submissions',
  path: '/lecturer/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/student/assessments',
  path: '/student/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/student/grades',
  path: '/student/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSubmissionsRoute = StudentSubmissionsRouteImport.update({
  id: '/student/submissions',
  path: '/student/submissions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/assessments': typeof LecturerAssessmentsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/grading': typeof LecturerGradingRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/profile': typeof LecturerProfileRoute
  '/lecturer/statistics': typeof LecturerStatisticsRoute
  '/lecturer/submissions': typeof LecturerSubmissionsRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/submissions': typeof StudentSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/assessments': typeof LecturerAssessmentsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/grading': typeof LecturerGradingRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/profile': typeof LecturerProfileRoute
  '/lecturer/statistics': typeof LecturerStatisticsRoute
  '/lecturer/submissions': typeof LecturerSubmissionsRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/submissions': typeof StudentSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/academic': typeof AdminAcademicRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lecturer/assessments': typeof LecturerAssessmentsRoute
  '/lecturer/courses': typeof LecturerCoursesRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/grading': typeof LecturerGradingRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/profile': typeof LecturerProfileRoute
  '/lecturer/statistics': typeof LecturerStatisticsRoute
  '/lecturer/submissions': typeof LecturerSubmissionsRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/submissions': typeof StudentSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/academic'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/statistics'
    | '/admin/users'
    | '/lecturer/assessments'
    | '/lecturer/courses'
    | '/lecturer/dashboard'
    | '/lecturer/grading'
    | '/lecturer/materials'
    | '/lecturer/profile'
    | '/lecturer/statistics'
    | '/lecturer/submissions'
    | '/student/assessments'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/grades'
    | '/student/profile'
    | '/student/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/academic'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/statistics'
    | '/admin/users'
    | '/lecturer/assessments'
    | '/lecturer/courses'
    | '/lecturer/dashboard'
    | '/lecturer/grading'
    | '/lecturer/materials'
    | '/lecturer/profile'
    | '/lecturer/statistics'
    | '/lecturer/submissions'
    | '/student/assessments'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/grades'
    | '/student/profile'
    | '/student/submissions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/academic'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/statistics'
    | '/admin/users'
    | '/lecturer/assessments'
    | '/lecturer/courses'
    | '/lecturer/dashboard'
    | '/lecturer/grading'
    | '/lecturer/materials'
    | '/lecturer/profile'
    | '/lecturer/statistics'
    | '/lecturer/submissions'
    | '/student/assessments'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/grades'
    | '/student/profile'
    | '/student/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAcademicRoute: typeof AdminAcademicRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LecturerAssessmentsRoute: typeof LecturerAssessmentsRoute
  LecturerCoursesRoute: typeof LecturerCoursesRoute
  LecturerDashboardRoute: typeof LecturerDashboardRoute
  LecturerGradingRoute: typeof LecturerGradingRoute
  LecturerMaterialsRoute: typeof LecturerMaterialsRoute
  LecturerProfileRoute: typeof LecturerProfileRoute
  LecturerStatisticsRoute: typeof LecturerStatisticsRoute
  LecturerSubmissionsRoute: typeof LecturerSubmissionsRoute
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSubmissionsRoute: typeof StudentSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academic': {
      id: '/admin/academic'
      path: '/admin/academic'
      fullPath: '/admin/academic'
      preLoaderRoute: typeof AdminAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/assessments': {
      id: '/lecturer/assessments'
      path: '/lecturer/assessments'
      fullPath: '/lecturer/assessments'
      preLoaderRoute: typeof LecturerAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/courses': {
      id: '/lecturer/courses'
      path: '/lecturer/courses'
      fullPath: '/lecturer/courses'
      preLoaderRoute: typeof LecturerCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/dashboard': {
      id: '/lecturer/dashboard'
      path: '/lecturer/dashboard'
      fullPath: '/lecturer/dashboard'
      preLoaderRoute: typeof LecturerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/grading': {
      id: '/lecturer/grading'
      path: '/lecturer/grading'
      fullPath: '/lecturer/grading'
      preLoaderRoute: typeof LecturerGradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/materials': {
      id: '/lecturer/materials'
      path: '/lecturer/materials'
      fullPath: '/lecturer/materials'
      preLoaderRoute: typeof LecturerMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/profile': {
      id: '/lecturer/profile'
      path: '/lecturer/profile'
      fullPath: '/lecturer/profile'
      preLoaderRoute: typeof LecturerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/statistics': {
      id: '/lecturer/statistics'
      path: '/lecturer/statistics'
      fullPath: '/lecturer/statistics'
      preLoaderRoute: typeof LecturerStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/submissions': {
      id: '/lecturer/submissions'
      path: '/lecturer/submissions'
      fullPath: '/lecturer/submissions'
      preLoaderRoute: typeof LecturerSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/student/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/student/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/submissions': {
      id: '/student/submissions'
      path: '/student/submissions'
      fullPath: '/student/submissions'
      preLoaderRoute: typeof StudentSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAcademicRoute: AdminAcademicRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminUsersRoute: AdminUsersRoute,
  LecturerAssessmentsRoute: LecturerAssessmentsRoute,
  LecturerCoursesRoute: LecturerCoursesRoute,
  LecturerDashboardRoute: LecturerDashboardRoute,
  LecturerGradingRoute: LecturerGradingRoute,
  LecturerMaterialsRoute: LecturerMaterialsRoute,
  LecturerProfileRoute: LecturerProfileRoute,
  LecturerStatisticsRoute: LecturerStatisticsRoute,
  LecturerSubmissionsRoute: LecturerSubmissionsRoute,
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSubmissionsRoute: StudentSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
